algoritmo "enquanto for diferente de 5"
// Função :
// Autor :
// Data : 14/07/2024
// Seção de Declarações 
var
n:inteiro
resultado: inteiro




inicio
      resultado<- 0
      Escreval("digite um número")
      leia(n)
      Enquanto n<>5 faca
      resultado<-resultado+n
      Escreval("digite um número")
      leia(n)
      fimenquanto
      Escreval("total:", resultado)


      
      
fimalgoritmo
