algoritmo "enquanto faca fatorial"
// Função :
// Autor :
// Data : 15/07/2024
// Seção de Declarações 
var

   numero: inteiro
   contador: inteiro
   fatorial:inteiro

inicio

      Escreval("digite um número")
      leia(numero)
      contador<-1
      fatorial<-  numero
      enquanto (contador<numero) faca
      fatorial<-fatorial*contador
      contador<- contador+1
      fimenquanto
      Escreval(" o fatorial de", numero, "é", fatorial)
      
fimalgoritmo
