algoritmo "semnome"
// Função :
// Autor :
// Data : 13/07/2024
// Seção de Declarações 
var

   numero:inteiro
   
   
inicio

      Escreval("digite um número")
      leia(numero)

      se (numero>10) entao
      
      
      Escreval(numero,"este número é maior que 10")
      senao
      
      
      Escreval("este número é menor que 10")
      
      fimse
      
fimalgoritmo
