algoritmo "repita 50 números pares"
// Função :
// Autor :
// Data : 20/07/2024
// Seção de Declarações 
var
   numeropar, quantidadeDeVezes: inteiro
   
inicio

      numeropar <- 2
      quantidadeDeVezes <- 1
      repita
            Escreval(numeropar)
            numeropar<- numeropar+2
            quantidadeDeVezes <- quantidadeDeVezes+ 1
      ate quantidadeDeVezes>50


fimalgoritmo
