algoritmo "se com e"
// Função :
// Autor :
// Data : 13/07/2024
// Seção de Declarações 
var

   numero: inteiro
inicio

      Escreval("digite um número")
      leia(numero)
      se (numero>=2) e (numero<=10) entao
      Escreval("O", numero, "está em um intervalo entre 2 e 10")
      senao
      
           Escreval("o número digitado está fora do intervalo entre 2 e 10")
           
      fimse
fimalgoritmo

